language: node_js
sudo: true
dist: trusty
node_js:
  - 8
  - 11
install:
  - npm install
script: npm run test
notifications:
  email:
    on_failure: change
after_success:
    - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'